class CategoriesController < ApplicationController

  before_filter :require_login, only: :update

  # GET root without subdomain
  def choose_language
    # remove any subdomains
    return redirect_to root_url(subdomain: false) if request.subdomain.present?

    render 'choose_language', layout: 'choose_language_layout'
  end

  # GET root with subdomain ruby, js or design
  #   and GET /categories
  def index
    # remove any unknown subdomains
    return redirect_to root_url(subdomain: false) unless request.subdomain.match(/\b(ruby|js|design)\b/)

    @categories = Category.language(request.subdomain).has_repos.order_ks
  end

  # GET /categories/:id
  def show
    # :id is generated by friendly_id
    @category = Category.find(params[:id])

    # If an old id or a numeric id was used to find the record, then
    #   the request path will not match the post_path, and we should do
    #   a 301 redirect that uses the current friendly id.
    if request.path != category_path(@category)
      return redirect_to @category, status: :moved_permanently
    end

    @repos = Repo.tagged_with(@category.name).order_ks


  end

  # PUT /categories/:id
  def update
    @category = Category.find_by_slug(params[:id])

    if @category.update_attributes(params[:category])
      flash[:notice] = 'Category description updated.'
      redirect_to action: 'show'
    else
      flash[:alert] = 'Category description could not be updated.'
      redirect_to action: 'show'
    end
  end



end
